### ISSUE TITLE
Pressing and holding Return causes Atuin to error out

### ISSUE THREAD

**Issue by ajeetdsouza** [ellie/atuin#474]
Atuin: v0.10.0
Fish: v3.5.0

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/1777663/177548692-e5ee512b-0eef-48b4-b61f-f70dd4320acd.png">

Here's a full backtrace:

```sh
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1187:9
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: std::io::stdio::_print
   3: atuin::command::client::init::Cmd::run
   4: atuin::command::client::Cmd::run::{{closure}}
   5: tokio::runtime::basic_scheduler::Context::enter
   6: tokio::macros::scoped_tls::ScopedKey<T>::set
   7: tokio::runtime::basic_scheduler::BasicScheduler::block_on
   8: atuin::command::client::Cmd::run
   9: atuin::main
```

What happens is that pressing Return too fast causes stdout to be closed, which makes `println!` break.

See how I've handled it in [zoxide](https://github.com/ajeetdsouza/zoxide): https://github.com/ajeetdsouza/zoxide/blob/e7cc34b359d2acbe92a3d970d328da186e27df61/src/error.rs#L18

**Comment by ellie** [comment]
I haven't been able to replicate this one on the latest (v16), do you know if it's still occuring for you?

Sorry for the delay in getting to this :/

**Comment by SeniorMars** [comment]
Hello. This is still occurring to me!

```
λ in ~/.co/fish ❯❯ atuin -V
atuin 18.3.0
```

```
λ in ~/.co/fish ❯❯ thread 'main' panicked at library/std/src/io/stdio.rs:1088:9:
failed printing to stdout: Broken pipe (os error 32)
stack backtrace:
   0:        0x101af0650 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h675959c2bbf9d3a2
   1:        0x101b12e58 - core::fmt::write::h08532690b0743eb9
   2:        0x101adaf8c - std::io::Write::write_fmt::h852142c1571d3144
   3:        0x101af04a8 - std::sys_common::backtrace::print::h9ecc17f349547d07
   4:        0x101b042b8 - std::panicking::default_hook::{{closure}}::h42085904defa4a64
   5:        0x101b03ff4 - std::panicking::default_hook::h82821fda9c744777
   6:        0x101b04654 - std::panicking::rust_panic_with_hook::h901bb6e8a935328d
   7:        0x101af0b30 - std::panicking::begin_panic_handler::{{closure}}::h60dbc70ce022bacb
   8:        0x101af0870 - std::sys_common::backtrace::__rust_end_short_backtrace::h20e33c3c7f244fe0
   9:        0x101b0439c - _rust_begin_unwind
  10:        0x101b69bd0 - core::panicking::panic_fmt::hb85c81430cde0818
  11:        0x101af0028 - std::io::stdio::_print::h0cc82eec4b2c32ee
  12:        0x1011ecaa0 - atuin::command::client::init::fish::init_static::haa4a206e09fe0ebe
  13:        0x100fa6b48 - atuin::command::client::Cmd::run_inner::{{closure}}::h2d1b1f3da9c5a2b2
  14:        0x10127bf08 - tokio::runtime::runtime::Runtime::block_on::h80e2188fffff8f40
  15:        0x1011f1d7c - atuin::main::ha8225added4ca7ff
  16:        0x1010fa1cc - std::sys_common::backtrace::__rust_begin_short_backtrace::h6612baa4d57c8583
  17:        0x10116aed8 - std::rt::lang_start::{{closure}}::ha255e5e85a8df294
  18:        0x101b042f0 - std::panicking::try::h9a9c0ea66b97216e
  19:        0x101afea04 - std::rt::lang_start_internal::h01f1f47178c1ba1d
  20:        0x1012078b0 - _main
  ```
  
  For me it's when i make my terminal bigger/small too fast. I have no idea how to fix this.

**Comment by tradiff** [comment]
I had the same problem, and solved it by wrapping the atuin config in config.fish with an is-interactive check:
```
if status --is-interactive
    atuin init fish | source
end
```

If anyone finds this thread with a similar issue, give that a try.

I'm new to fish, but I'm guessing it was something like the prompt is executing some commands to get various data for the prompt, and those commands were unnecessarily loading atuin.
