### ISSUE TITLE
thread 'main' panicked at 'failed to find ATUIN_SESSION - check your shell setup: NotPresent', atuin-client/src/database.rs:29:35 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### ISSUE THREAD

**Issue by JanisZhang** [ellie/atuin#595]
Hi, I got this error when I'm trying to execute atuin command (I'm using xUbuntu v20.04): 
```
thread 'main' panicked at 'failed to find ATUIN_SESSION - check your shell setup: NotPresent', atuin-client/src/database.rs:29:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Is there something wrong with my configuration? Thank you

**Comment by JanisZhang** [comment]
Hi, after restarting the terminal, the issue was fixed. :)

Closing this one....
